---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-ceph-mon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rook-ceph-mon
    template:
      engineVersion: v2
      data:
        ceph-username: "{{ .ROOK_CEPH_USER }}"
        rook-ceph-mon-endpoints: "{{ .ROOK_CEPH_MON_ENDPOINTS }}"
  dataFrom:
    - extract:
        key: rook-ceph-mon
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ceph-admin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ceph-admin-secret
    template:
      engineVersion: v2
      data:
        ceph-secret: "{{ .ROOK_CEPH_SECRET }}"
  dataFrom:
    - extract:
        key: ceph-admin-secret
