apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-cache
spec:
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  storageClassName: tdarr-cache-class
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_IP}
    path: /volume1/tdarr-cache
  # Note: The first two options are strictly for NFSv4.2
  # "nfsvers=4.2", "nconnect=8",
  mountOptions: ["hard", "noatime"]
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tdarr-cache
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: tdarr-cache-class
  resources:
    requests:
      storage: 500Gi
---
 apiVersion: storage.k8s.io/v1
 kind: StorageClass
 metadata:
   name: tdarr-cache-class
 parameters:
   server: 10.10.96.10
   share: /volume1/tdarr-cache
 provisioner: nfs.csi.k8s.io
 reclaimPolicy: Retain
 volumeBindingMode: Immediate
