apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-temp
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-hostpath
  local:
    path: /tdarr-temp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-one
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tdarr-temp-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 500Gi

