apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-cache
spec:
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  storageClassName: tdarr-cache
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_IP}
    path: /volume1/tdarr-cache
  # Note: The first two options are strictly for NFSv4.2
  # "nfsvers=4.2", "nconnect=8",
  mountOptions: ["hard", "noatime"]
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tdarr-cache-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: tdarr_cache
  resources:
    requests:
      storage: 500Gi

