---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minecraft-survival
    template:
      engineVersion: v2
      data:
        whitelist: "{{ .MINECRAFT_SURVIVAL_WHITELIST}}"
        ops: "{{ .MINECRAFT_SURVIVAL_OPS}}"
        cf_api_key: "{{ .CF_API_KEY }}"
  dataFrom:
    - extract:
        key: minecraft-survival
