---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minecraft
  data:
    - secretKey: whitelist
      remoteRef:
        key: MINECRAFT_SURVIVAL_WHITELIST
    - secretKey: ops
      remoteRef:
        key: MINECRAFT_SURVIVAL_OPS
