---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minecraft
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      minecraft:
        replicas: 1
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: java21@sha256:6e1d3c0dc96379b7f85a7519873ba6ce60cdc0da82d76434c06e40a726d4720e
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  periodSeconds: 60
                  initialDelaySeconds: 300
                  exec:
                    command: ["mc-health"]
              readiness:
                enabled: true
                custom: true
                spec:
                  periodSeconds: 60
                  initialDelaySeconds: 300
                  exec:
                    command: ["mc-health"]
              startup:
                enabled: true
                custom: true
                spec:
                  initialDelaySeconds: 300
                  periodSeconds: 1
                  failureThreshold: 1200
                  exec:
                    command: ["mc-health"]
            env:
              # Server Configuration
              ## General
              - name: EULA
                value: 'true'
              - name: SERVER_NAME
                value: 'GGMC'
                #  - name: TYPE
                #    value: FABRIC
                #  - name: FORCE_REDOWNLOAD
                #    value: 'true'

              # renovate: depName=minecraft datasource=custom.minecraft
              #- name: VERSION
              #  value: 1.21
              - name: MOTD
                value: 'be nice'
              - name: DIFFICULTY
                value: hard
              - name: SPAWN_PROTECTION
                value: '0'
                # - name: SEED
                # value: '-2135836821937050197'
              - name: ENABLE_WHITELIST
                value: 'false'
              # Logging
              - name: ENABLE_ROLLING_LOGS
                value: 'true'
              - name: LOG_TIMESTAMP
                value: 'true'
              # Performance
              #- name: JVM_XX_OPTS
              #  value: '-XX:MaxRAMPercentage=75'
              - name: MEMORY
                value: 16G
                # - name: MAX_MEMORY
                #   value: 8G
                # - name: USE_AIKAR_FLAGS
                #   value: 'true'
                # - name: SNOOPER_ENABLED
                #   value: 'false'
                # - name: VIEW_DISTANCE
                #   value: '14'
              ## Mods
              # - name: REMOVE_OLD_MODS
              #   value: 'true'
              # - name: MODRINTH_DEFAULT_VERSION_TYPE
              #   value: release
              # - name: MODRINTH_PROJECTS
              #   value: "fabric-api,spark,floodgate:beta"
              # - name: VANILLA_TWEAKS_SHARE_CODES
              #   value: "ozxXFS"

              - name: MOD_PLATFORM
                value: 'AUTO_CURSEFORGE'
              - name: CF_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: minecraft-survival
                    key: cf_api_key
              - name: CF_PAGE_URL
                value: 'https://www.curseforge.com/minecraft/modpacks/all-the-mods-9'

              ## RCON
              - name: RCON_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: minecraft-rcon
                    key: rcon_password
              - name: ENABLE_QUERY
                value: 'true'
              # Whitelist / Ops
              - name: WHITELIST
                valueFrom:
                  secretKeyRef:
                    name: minecraft-survival
                    key: whitelist
              - name: EXISTING_WHITELIST_FILE
                value: SYNC_FILE_MERGE_LIST
              - name: OPS
                valueFrom:
                  secretKeyRef:
                    name: minecraft-survival
                    key: ops
              - name: EXISTING_OPS_FILE
                value: SYNCHRONIZE
              ## External resources - remove after first boot
              #WORLD: 'http://192.168.1.234/server-world.zip'
            #securityContext:
              # runAsUser: 1000
              # runAsGroup: 0
              # fsGroup: 1000
            resources:
              requests:
                cpu: 1000m
                memory: 24Gi
              limits:
                memory: 32Gi
    service:
      minecraft:
        controller: minecraft
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          java:
            port: 25565
            protocol: TCP
    ingress:
      minecraft:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: mc.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: minecraft
                  port: java
        tls:
          - hosts:
              - mc.${SECRET_DOMAIN}
    persistence:
      data:
        existingClaim: ${VOLSYNC_CLAIM}

