# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: docker-registry
    template:
      engineVersion: v2
      data:
        values.yaml: |
          secrets:
            htpasswd: "{{ .DOCKER_REGISTRY_HTPASSWD }}"
  dataFrom:
    - extract:
        key: docker-registry
