---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: docker-registry
    template:
      engineVersion: v2
      data:
        values:
          secrets:
            htpasswd: "{{ .DOCKER_REGISTRY_HTPASSWD }}"
  dataFrom:
    - extract:
        key: docker-registry
