---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: storage
  annotations:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/instance: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-hostpath
