apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:nmUYx/Af3/Ya/OLCz+fRsD48mMbVZwOdQNMTNkMIQRpMRpyP,iv:7c/HDNzMvzD0O4Y1XhNN4+Yl+UfBtVu/ALN0QkR1bdc=,tag:W/k2NJ+JoHep48QTnwZruQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:UlhoAA1g3+VVwhOFv+PTECHTMVcQyCx+mdk6xYtrC/2OfYOyV7HbWkk9CkTL9/bQ6GSP6VaDC0k70WCqn1toa3utK0sAksmttqLqq5b7Tpbh7pNG6mBYZilUu8v3u/Q85DwwcM0I//waA4o31W5SBxfuneP3y+2+ilMlZ+CM+CIFz8a6BCFjxhfGE+2prHAT9yWqLQwXw+qzDY1ViyO7FaLtc68VgZjb9MWifWwJaQ==,iv:JVFH5fhnxjb4XT+toYlshIZS3fgWEU0iyQF6X4336zo=,tag:vxfRFXlg5avgwCgYC7NiZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rc6t0klkczsvnjhpl9aghvfphqpx6ue2xdwp8rk2c2hpcy3fgv3sh7cj9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNFNCS1pBT3ZXRWU3TThm
            eGVGN01mQ0Z0YUVFMEwya3hyOVdRbTU1NHpNCmpiZXIxa05TS1J4eEp3SG4wbWVi
            MUJ0b3Z4MXVhYXNBV0R6VytUVjRLbXMKLS0tIGxLNjBLbXVGOVo2N2lkK1lEZ01n
            cUxDUFl0S2dUbUdHSXl4UTg2VUF6cHcKMbBOHaauGep0JinxjsoTo7zw5vQ+GX9j
            c2jYpB9MHHhihx8oca+YBx4C/vDvY9m58MhUsBMHQEg1bqM5OxdCww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T15:48:21Z"
    mac: ENC[AES256_GCM,data:3U2Xbc4ZA/vm2FMHKc+gbsCgOkiDfgaFvQ2FsBQeZ7hGHShYg8XeveEfbOkcslbRPKzCaP2SVQLQVvCftqcMR6e4nMmhokm3UBxr08dcTCUGDXAYDhbj5FM1HT+Jt3IX4rSeZQyDJxn8Bj4k6mQzKvWxd4uofqJLMChSJHlGnD4=,iv:WpWfjI2Zm+YDlte21Azu3baeuD89eYvgvlW5GJyh1+E=,tag:CGne6nGo/ju6Thm25f9dug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
