# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: docker-registry
    template:
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .DOCKER_REGISTRY_CONFIG_JSON }}"
  dataFrom:
    - extract:
        key: docker-registry
