apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:cyYjtaELYEqYiZn0nB9hcM/qoG5kf0qqPlm09iM/HZGu90yr6kntXj+5SM1UJENKwTc=,iv:oMr1GDM4QO2KZJjbTyQZ5KZ1MmE1SjtDlBdW6SB7y6Q=,tag:MpCPXLUMEHoHqae08WWCWw==,type:str]
    admin-user: ENC[AES256_GCM,data:bEcwg6g=,iv:cCsLJM0t8cnFIqgRPA1wc/tAX6Zg7fDACFh9qtfFcAU=,tag:f/lkhrUz5TuHZpAYndrlzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rc6t0klkczsvnjhpl9aghvfphqpx6ue2xdwp8rk2c2hpcy3fgv3sh7cj9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRFM1dW81OXI4Q0E4WjRw
            UGFOOTM1b0hQZkRlTkEzRVB3Qkh1bTdUcVJFCjZPMnN4MDh6UmIzc1dwMzBxRXE4
            d0VjRkd2S1hCUFJDZ3pzcGJPNWdRWWMKLS0tIHIxcjB5c3dxTU5BL1NpQUlqWnR4
            dlZ1U2U3ZzcvditTNFBSdXRLbkNvbGcK87oUkyiHKR49th0326rbq0U5BObSM6HP
            h9mePy96qSY/cVJpLReHBIZf6MckJZ4SRN3sm1FkljxlcQAYgeDyGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T15:48:25Z"
    mac: ENC[AES256_GCM,data:Sj5T14PJG2KO78ynQ42ZzKSMAfDBipW+reW77QP4Xo4qODr9+tegN/mL7ylepDrUH4u6f8n4qxpc2N0X+gX3595Nhka+ZEA1zPkqTcnePq2OfNmQ660NW/bhW+jhblD32SVI4syH8GODtNtw7bHnHnye3fckcAhHn8cPU1uAnnk=,iv:EccXk+BbWdrTlXBUJQYXzHGNGKD8fm6rsrBrbOoseGw=,tag:t7JX2RO1OYdlIEO5thg1wA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
