---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-hostpath
