---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: local-hostpath
