---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./mmc-alloy-external/service.yaml
  - ./namespace.yaml
  - ./hajimari/ks.yaml
  - ./authelia/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./glauth/ks.yaml
  - ./secret-generator/ks.yaml
