---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.10.96.10
  share: /volume1/k3s
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
