---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki
    template:
      engineVersion: v2
      data:
        MINIO_USER: "{{ .MINIO_ROOT_USER }}"
        MINIO_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: minio
