---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.45.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: openebs
      namespace: openebs-system
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      analytics:
        reporting_enabled: false
      server:
        log_level: info
      commonConfig:
        replication_factor: 1
      ingester:
        chunk_encoding: snappy
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-04-01" # quote
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      limits_config:
        retention_period: 14d
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 50Gi
      extraEnv:
        - name: JAEGER_ENDPOINT
          value: "http://mmc-alloy-external.default.svc.cluster.local:14268/api/traces"
          # This sets the Jaeger endpoint where traces will be sent.
          # The endpoint points to the mmc-alloy service in the default namespace at port 14268.

        - name: JAEGER_AGENT_TAGS
          value: 'cluster="prod",namespace="default"'
          # This specifies additional tags to attach to each span.
          # Here, the cluster is labeled as "prod" and the namespace as "default".

        - name: JAEGER_SAMPLER_TYPE
          value: "ratelimiting"
          # This sets the sampling strategy for traces.
          # "ratelimiting" means that traces will be sampled at a fixed rate.

        - name: JAEGER_SAMPLER_PARAM
          value: "1.0"
          # This sets the parameter for the sampler.
          # For ratelimiting, "1.0" typically means one trace per second.
    gateway:
      replicas: 0
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    test:
      enabled: false
