---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: vector-agent
      namespace: observability
    - name: vector-aggregator
      namespace: observability
  values:
    gateway:
      replicas: 1
      image:
        registry: ghcr.io
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: loki.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
      rules:
        searchNamespace: ALL
        folder: /rules/fake
    lokiCanary:
      enabled: false
    test:
      enabled: false
