---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.6.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: vector-agent
      namespace: observability
    - name: vector-aggregator
      namespace: observability
  values:
    deploymentMode: SingleBinary
    loki:
      ingester:
        chunk_encoding: snappy
      storage:
        type: local
      schemaConfig:
        configs:
          - from: "2024-04-01" # quote
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      structuredConfig:
        auth_enabled: false
        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095
          grpc_server_max_recv_msg_size: 8388608
          grpc_server_max_send_msg_size: 8388608
        limits_config:
          ingestion_burst_size_mb: 128
          ingestion_rate_mb: 64
          max_query_parallelism: 100
          per_stream_rate_limit: 64M
          per_stream_rate_limit_burst: 128M
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          retention_period: 30d
          shard_streams:
            enabled: true
          split_queries_by_interval: 1h
        query_scheduler:
          max_outstanding_requests_per_tenant: 4096
        frontend:
          max_outstanding_per_tenant: 4096
        analytics:
          reporting_enabled: false
    singleBinary:
      replicas: 1
    backend:
      replicas: 0
    gateway:
      replicas: 1
      image:
        registry: ghcr.io
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        ingressClassName: internal
        hosts:
          - host: loki.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls: []
    read:
      replicas: 0
    write:
      replicas: 0
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
      rules:
        searchNamespace: ALL
        folder: /rules/fake
    lokiCanary:
      enabled: false
    test:
      enabled: false
    minio:
      enabled: true
