---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.10.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: openebs
      namespace: openebs-system
  values:
    deploymentMode: SimpleScalable
    loki:
      auth_enabled: false
      analytics:
        reporting_enabled: false
      server:
        log_level: info
      commonConfig:
        replication_factor: 1
      ingester:
        chunk_encoding: snappy
      storage:
        type: s3
        bucketNames:
          chunks: "loki-chunks"
          ruler: "loki-ruler"
          admin: "loki-admin"
        s3:
          # s3 URL can be used to specify the endpoint, access key, secret key, and bucket name
          # s3: s3://access_key:secret_access_key@custom_endpoint/bucket_name
          # AWS endpoint URL
          endpoint: "http://minio-api.network.svc.cluster.local"
          # AWS region where the S3 bucket is located
          region: us-east-1
          # AWS secret access key
          # AWS signature version (e.g., v2 or v4)
          # signatureVersion: <your-signature-version>
          # Forces the path style for S3 (true/false)
          s3ForcePathStyle: true
          # Allows insecure (HTTP) connections (true/false)
          insecure: true
          # HTTP configuration settings
          http_config: {}

      schemaConfig:
        configs:
          - from: "2024-04-01" # quote
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      limits_config:
        retention_period: 14d
    singleBinary:
      replicas: 0
      # persistence:
      #   enabled: true
      #   storageClass: openebs-hostpath
      #   size: 50Gi
    gateway:
      replicas: 0
    backend:
      replicas: 1
    read:
      replicas: 1
    write:
      replicas: 1
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    test:
      enabled: false

  valuesFrom:
    - kind: Secret
      name: loki
      valuesKey: MINIO_LOKI_USER
      targetPath: loki.storage.s3.accessKeyId
    - kind: Secret
      name: loki
      valuesKey: MINIO_LOKI_PASSWORD
      targetPath: loki.storage.s3.secretAccessKey
