---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-loki 
  namespace: observability 
  labels:
    app.kubernetes.io/name:  loki
    app.kubernetes.io/instance: loki
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath  
