apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:wRBny49L7WIhgUudBz2u5Ej0kJnTo7cA6IUvXjVaIG5ihXzOgNI7BsIC12VYGjPZa6hpwTVJyy4L1xRs,iv:Xf+1799FlTKCf77CS2KwFw4B/U/BSw2nJPT3f7IitKw=,tag:nj9CUIo8Qk2OGo6VTQonbg==,type:str]
    username: ENC[AES256_GCM,data:yhYYFKY=,iv:C6IqpS6UVcYDnlChxJFrUDjyfYA5c1zwb/16tMT/MZ8=,tag:wArzucD7VkJcPRbVTs4IQw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rc6t0klkczsvnjhpl9aghvfphqpx6ue2xdwp8rk2c2hpcy3fgv3sh7cj9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdzY4R0g3VlZiMlRwbjJi
            UlRoaFBZUUNrd3dURTd1Y2hEVXJ3TjZ5NUE4CnFmdnVCaTZ4OG9oRGtxbzlUeDVh
            Y1dlUzR6eE9WM0xDQndzMjc0SE9FbEEKLS0tIHdsYU13R1l5Z1llOHh6L2I2MWhT
            UUtHQUdKZkRLY2pNa0hLRm85WW1wN2sK5dBqxZiL286Qut8WFW0+CAYbbWGKrLH4
            dgD3OwsYRyYU1mfX/9d45lbHUlz72t82sNCk4hZShkjzFsveRMaorQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T16:24:56Z"
    mac: ENC[AES256_GCM,data:ipKjLpK3jeFilUEawCfIHyWU+Q4CMcRZEY+kBk9Id7TFJ2bb9JCRuHPstUwwP92TXeMtH9HAEuo9k0cRC2u+zDs2TTef9sh5/C19K1UDnsgL0DKe/hRVLg4pQFuIwavyn1qzGcnFG0bxv7B557Lvz+2e2Akg0WAiVuKdHf2stcY=,iv:ETLusYnv9UAXE9RtwQ1R7C8fn6GVBlqEcBnUM1INBb8=,tag:RT3o6v4DWgVS+EjjumZEzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
