---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: logs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: logs
    template:
      engineVersion: v2
      data:
        username: "{{ .GRAFANA_CLOUD_K8S_POLICY_ID }}"
        password: "{{ .GRAFANA_CLOUD_LOKI_INSTANCE_USER }}"
        endpoint: "{{ .GRAFANA_CLOUD_LOKI_INSTANCE_URL }}"
  dataFrom:
    - extract:
        key: grafana
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traces
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: traces
    template:
      engineVersion: v2
      data:
        password: "{{ .GRAFANA_CLOUD_K8S_POLICY_ID }}"
        username: "{{ .GRAFANA_CLOUD_TEMPO_INSTANCE_USER }}"
        endpoint: "{{ .GRAFANA_CLOUD_TEMPO_INSTANCE_URL }}"
  dataFrom:
    - extract:
        key: grafana

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: metrics
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: metrics
    template:
      engineVersion: v2
      data:
        password: "{{ .GRAFANA_CLOUD_K8S_POLICY_ID }}"
        username: "{{ .GRAFANA_CLOUD_PROM_INSTANCE_USER }}"
        endpoint: "{{ .GRAFANA_CLOUD_PROM_INSTANCE_URL }}"
  dataFrom:
    - extract:
        key: grafana
