---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: playit
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app playit
  interval: 10m
  path: ./kubernetes/apps/network/playit/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  postBuild:
    substitute:
      APP: *app
      APP_UID: "568"
      APP_GID: "568"
  dependsOn:
    - name: external-secrets-stores
    - name: external-dns
