apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:RdXzdYR69IkGrrOG/CU6wQ==,iv:bBq967WPPH80e8R6ho1YACJTAldfDUGvtWgKrqnffmE=,tag:sHL1RzKp/adtrRfGFPMzjA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vhO6yAQd1OK9yqlj+CQg0TBvjUA1iLiBwNbYqaXQRN6CIFZ0,iv:3gvz7S4YqnaG9n6XQuU/kr1IdRSFkTLA+Uhp7Kih7Oc=,tag:6NVzVqdkAwPE5mF0uOwu7g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:AhrLUhcgFoiAUw==,iv:w90MDugbSt063Q4kJJs/rZ8ekamTWFjfqvYpUkhExRw=,tag:EFerjSf83SHGaErTyqt13Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rc6t0klkczsvnjhpl9aghvfphqpx6ue2xdwp8rk2c2hpcy3fgv3sh7cj9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzK2JxUExRQ2p5L29LODBv
            SjdudTUwa29xSGcxMXZtOGRORndhaDRrb25vCkVQZHN2UTd3VUhRejd4QjBxSldo
            cnNSZlQ4bm1pYUIvV3lId1FHTFh6TGsKLS0tIE1KRW9xWU1VbG8xWFIvemlVQndD
            ZVF2MW54K0EyNEoydjNKelRGQ1lnMUUKK924tPTALtyJuiNgFcaPFAybH3FLDsuo
            06Y2I7KqzIWOh04gnGQM0gYfJEHR6kT/mVDmYLraS1Gi6cfYRiik1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T15:48:20Z"
    mac: ENC[AES256_GCM,data:QWOQGpg6rIF/5v5R03DLdbic9tApiKPdDcGyCA8w/wookx+s3413b5MJ60KvnlSZU0HQNaMdpnMUbhDH/KAMcjHc2xvLTrqw1qULmDjnP5P/zkI9fFqpRCRmgm4CEFThf3DkIoj6usvllP6iwI6+mXM1FO+ted/S05V8keHuiX4=,iv:zzaKazQLCVLIZxEkSfQZ6FpfmYvCaxH7csZm65Vv9fk=,tag:zarz3jnqNkG9Q6YUqlY0EA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
