---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: photoprism
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: photoprism-secret
    template:
      engineVersion: v2
      data:
        PHOTOPRISM_ADMIN_USER: admin
        PHOTOPRISM_ADMIN_PASSWORD: "{{ .PHOTOPRISM_ADMIN_PASSWORD }}"
        PHOTOPRISM_DATABASE_DRIVER: mysql
        PHOTOPRISM_DATABASE_SERVER: mariadb.database.svc.cluster.local:3306
        PHOTOPRISM_DATABASE_NAME: photoprism
        PHOTOPRISM_DATABASE_USER: photoprism
        PHOTOPRISM_DATABASE_PASSWORD: "{{ .PHOTOPRISM_MARIADB_PASSWORD }}"
        PHOTOPRISM_OIDC_URI: "https://auth.${SECRET_DOMAIN}"
        PHOTOPRISM_OIDC_CLIENT: "{{ .PHOTOPRISM_OIDC_CLIENT }}"
        PHOTOPRISM_OIDC_SECRET: "{{ .PHOTOPRISM_OIDC_SECRET }}"
  dataFrom:
    - extract:
        key: photoprism
    - extract:
        key: mariadb
