---
# Manual PV for photoprism storage on forests node
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-storage-forests
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
  local:
    path: /var/lib/rancher/k3s/storage/photoprism-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - forests
