---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-cr-server
  namespace: games
  labels:
    app.kubernetes.io/name: minecraft-creative
    app.kubernetes.io/instance: minecraft-creative
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-hostpath
