apiVersion: batch/v1
kind: CronJob
metadata:
  name: laz-price-history
spec:
  # schedule: "5 * * * *"
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: docker-regstry-pull
          containers:
            - name: laz-price-history
              image: docker-registry.storage.svc.cluster.local:5000/laz-price-history
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
