---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: laz-price-history
spec:
  interval: 15m
  chart:
    spec:
      chart: ./helm/laz-price-history-chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: laz-price-history
        namespace: flux-system
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # https://github.com/bjw-s/helm-charts/tree/main/charts/other/app-template
    controllers:
      krr:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "5 * * * *"  # every hour on minute 5
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          cron:
            image:
              tag: latest
              repository: docker-registry.storage.svc.cluster.local:5000/laz-price-history
            args:
              - ls
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
