---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tube
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tube-secret
    template:
      engineVersion: v2
      data:
        ELASTIC_PASSWORD: "{{ .ELASTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: tube
    - extract:
        key: cloudnative-pg
