# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
stringData:
    token: ENC[AES256_GCM,data:ZeYlp7BYVL9/7j6pZFywVZwlaXkJS5DXfdw=,iv:TPpzrv/uWTW4vLvJQVXV+nxVktyUhCF4KzQ5qrpO7vc=,tag:9PCHXhl/LlRDLhw0KhPpHA==,type:str]
    1password-credentials.json: ENC[AES256_GCM,data:Rw/aVDOSI5oKjntNJewbYoHfZ4Omff2Wlgfp/O2/k6VxcHcZGTWAvpV4Y2mfn96v0IN17k9peeo5pQmTWFMsZTJT++Af5LmKoIiCW4URkz2j5aPkvcfL+ADejfJ/3h7Q9OpMthnoB5nr9D5uUKHEdqMUE1IwBSYP/zaYR09bBpk+GDPhZ1cCs+IFAm1OcPLli0jSJ2Lp3tBtr66Iti7WJOLmzJqQZ6yL4R+8XSTE1TzSyt40tuploewg1XigDOxfGaUnvLaxC1i597gH4f/RfawS0mt6wYrxyo5+Skvr5rX55zkxqKlu7swyk9HWPN3QNmzngz9xMWHMQgZv60RDegmnTxBZ/BxhFfnE2GLRT4j4r67EhNLGE3xlsNzf5z944z5/D6M9DjDRtReUVeBi2bv8GLh1iclkY/HFGq/FjbScNFPnrM/keZ08bnueiQfNMXsxNRPduaMwY/k80BjfVNftC2bGFrRPJWZRVKPYvBNM764kIy9vZnecCfJuilDwh09ZBw/L5+VZIYwFk707xKw3G0xemO15xJXY3jBnpqv2HhUxLsER+K6ZR+fCDnqYR2qhhLOzgPjlbXJjwTj6pJAjWdtmgcMx+KEvr9GHxtFgCrgXhitxygcmb+DAs9c2kD8LAA/VuY634ZY4jVkPB7VgRApN4D68NHOCXcAL7Bnb45Ts6Ln8+LpBLCpRMHdT/8QRCUkM02T3GsqCU8lO0hh/vIzlHQWgd8W4ZNJimfM0Duya7OUN/cFXgOLtLna9oe/nmDQL3DeOKy61TOt7kKU6dxrP5ucR1DwV1+210FNmNmdU2R0HpuWOyjSd23t2O9SY7vmqDgQjPwU9U0dCVedKWgfpY/McsquNiVwFYPyyH3KrGK9QI6+mQPOOXyyeVWb/L9DN06MMqw4gv3IDbdn7nCZjckXgj5VMHcultMitivOX60waN6Iuj7eexjiK7hnS7KFtGe/WFAg8YZe2ZaVwIfP/xitJF7P0uBTsil4r7AoDD1mPrp7XJ1MJ7rbEKaWx1mA3ReR7rQsUGx7FkL8+BeuPORMJQ1axD69hK10gtt6KWKe/MqYxZfW5uJ02qpNXxDCfOvrs8MwIbNtZ6so/4N8X4aOVfdrCDv2HZOvv1d6KcsPL2iO4YbdfkW4QTBQ3Ce9HWXTgKhKwfHWLFdo2hyKDOms/mpBsuEykiFEucFpn9JossCxqBBw5soKqMC9Y4K2O1ISTPLxqJXu29TmietQ3qE3YwFlJH0iEuBG+p6h6QaGUQWnSmmYtFKPQMvwvKCa4HqHkA4mxSr662q8EHK0GdT4Ce78u3vmOBMNGT/yT7ooZjHMGzIWffNK7EbN+HCOJqCgwQzhfnl6tS+dsee4AkXf+OBZcHOYWytP8n43d26nHf+z8jdiSD3WARYcnTVuUol30nC706iiMbFcIaiG7zkepROUzXca8c/8G7kWkosrSCyAP/lk+toj6IIlfhce3ctnTAGPPI1d5qTFHbafcwYfFpqo25pv8r43KfiR13t0Qfar61H/xdrYrmLURilCUjnVnURWdf92G6pdd4QCTPP/5u4wDP2TloNhryNpnVeuC/BYa+GhLFatSNDHEAgF4XoYmr7GbnF5ECLrhtvMx0c8dyTdTcQSFN/pWlY8NeJB//DpewA==,iv:TJMBmEP4cN0MbEEnJ82//Dozg1Xzv92XV4Dy2fo1iVo=,tag:7GS2YdGE9BuxZKKMKMdLgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rc6t0klkczsvnjhpl9aghvfphqpx6ue2xdwp8rk2c2hpcy3fgv3sh7cj9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2djI1QzFFa1FrZDVKaDZz
            TEkwS0NKNjdvZ2M3RTlRK3BkSU5SN1UybTFrCkk0ZHZtSjlrOFRxMWZxZG5Rd2tQ
            TThvSkhOQUNMQkhnaWkzcTM4QVhaVVkKLS0tIDhndGoxZVBIcTNqYTVYNW1qeFRX
            c1d6T2hZUXg0TFBoSTdoMUR2ZUQ0QU0KtUHNXNZctcCkvjpm1WGBBPlZ/Vs+dT6i
            J0KXTt0dq2cuSttYxGJXVIHahDZAm3eX1n45YTWx2t5yM9sgDBMrxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T11:51:41Z"
    mac: ENC[AES256_GCM,data:eAJmwOCNkZ/4X6EssDQrruRjR8txG7iM4r3ZzpSJjmu7FREGoxWCgvBVNkO6ig+KEper358mgbGfGhnpmJaV5xTBKCTi9bjQkfDyROioIWaRvMK2bU2nGO+3Y0F2b0fdnCJW6MJrjArgruHWOIMsU585yf8MsP2yNxt/knZqsrE=,iv:HmHM5urkew0RemhjVgIufKF7Cc22H4DLE2aOXbsu8Hg=,tag:xt96ESe76Jvcs/6MRanfjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
