---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: factorio-k2
  namespace: games
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: factorio-k2-secret
  data:
    - secretKey: rconpw
      remoteRef:
        key: RCONPW
    - secretKey: admin-whitelist.json
      remoteRef:
        key: ADMIN_WHITELIST_JSON
    - secretKey: server-settings.json
      remoteRef:
        key: SERVER_SETTINGS_JSON
