---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app factorio-k2
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: factoriotools/factorio
      tag: stable
    global:
      nameOverride: *app
    env:
      UPDATE_MODS_ON_START: "true"
      PORT: &port 34201
      RCON_PORT: &rcon 27017
    initContainers:
      copy-configmap:
        image: busybox@sha256:e3652a00a2fabd16ce889f0aa32c38eec347b997e73bd09e69c962ec7f8732ee
        imagePullPolicy: IfNotPresent
        command:
          - "sh"
          - "-c"
          - |
            mkdir -p /factorio/config
            cp -vL /helmconfig/* /factorio/config/
        volumeMounts:
          - name: helmconfig
            mountPath: /helmconfig/
          - name: config
            mountPath: /factorio/
        securityContext:
          runAsUser: 0
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 80
            enabled: false
            primary: false
          server:
            enabled: true
            port: *port
            protocol: UDP
          rcon:
            enabled: true
            primary: true
            port: *rcon
            protocol: TCP
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}

        hosts:
          - host: &host "factorio.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: factorio-k2
                  port: *port
        tls:
          - hosts:
              - *host

    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    #   fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /factorio
            readOnly: false
        existingClaim: factorio-k2-config-v1
      helmconfig:
        enabled: true
        type: "secret"
        name: factorio-k2
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 10
    resources:
      requests:
        cpu: 15m
        memory: 1555M
      limits:
        memory: 8006M
