apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:NnNb2gN6288fK8XP/oq6FgAl3OfzZty3wx47D9M0xygjGS4eg7hAZg==,iv:mRhwbst726i3VKQxkAPozZN+rYdq9d+9tCFSYNw7i38=,tag:OZWC4Bsiy66d6Vn6f2awEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rc6t0klkczsvnjhpl9aghvfphqpx6ue2xdwp8rk2c2hpcy3fgv3sh7cj9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTmxZVkRHWUZNS2NLUmVS
            eWdtZ1VtMEFYSFVNbTN5T3BOMlhybWNLa1Y4CnZPSStub3d1dUx1eDZyV0pKWkNl
            SG4xRW9uRjd1c21lZVlsRlRpbzhhdlEKLS0tIDUvZXNQQU80M3ZhNExkSDRzTVJU
            OW42dng3NkJuY2FVSHpvWUo4cElTTWMKydsqrlell7p+XfgHN/gkoN3XtWxc16os
            zWJeudvinCwlKiknOoVwezN8M4jVdP0lqU2yHeC6jpsQcZlf1FROag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T15:48:21Z"
    mac: ENC[AES256_GCM,data:hJnE7nrvu6t3RJUkXiipkxGOay3GEytR2EN6/0EiU84tG93YrIHPZBcpHB+AszG72mlBOgKgLpiPJrBcIoY7WOGBVS27mTujafdG24T3pgbT7DCrfzXbLY4XFIe4s6w/PNR6hPAMM9meZ9wb7E2ExrNk6OXENZ1ZwK65qBIe2J8=,iv:p4aZakiBzM9zn8/NJ4xk1Luqq5ZNEmOksSO5UHBUJps=,tag:TNT4v5YwoVG+USf8jaIKcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
